db:
  image: postgres
  volumes:
    - ./create_hstore_extension.sh:/docker-entrypoint-initdb.d/create_hstore_extension.sh:ro

data:
  image: cogniteev/echo
  volumes:
    - /var/www/image_data
    - ./images:/var/www/image_data/images
    - ./pycortex:/usr/local/share/pycortex

uwsgi:
  restart: always
  image: neurovault/neurovault_fs
  env_file: .env
  volumes_from:
    - data
  volumes:
    - .:/code
    - /var/www/static
  links:
    - db
    - redis
    working_dir: /code

nginx:
  restart: always
  image: nginx
  ports:
    - "80:80"
  volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    - ./uwsgi_params.par:/etc/nginx/uwsgi_params.par:ro
  volumes_from:
    - uwsgi
    - data
  links:
    - uwsgi

redis:
  restart: always
  image: redis

worker:
  image: neurovault/neurovault
  command: celery worker -A neurovault.celery -Q default -n default@%h
  volumes:
    - .:/code
  volumes_from:
    - uwsgi
    - data
  links:
    - db
    - redis
